name: Node.js CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm install

    - name: Run tests
      run: |
        npm test

    - name: Start server
      run: |
        npm start &
        sleep 10 
        
    - name: Deploy to Server via SSH
      if: success()
      uses: appleboy/ssh-action@v0.1.1
      with:
        host: ${{ secrets.SERVER_IP }}   
        username: ubuntu                 
        key: ${{ secrets.DEPLOY_SSH_KEY }}  
        script: |
          cd downloads/simple_nodeapp    
          git pull origin main           
          pm2 restart simple_nodeapp
