name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with: 
        node-version: '18'

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.IRFAN22.PEM }}

    - name: Connect to EC2 and Deploy
      env:
        PRIVATE_KEY: ${{ secrets.IRFAN22.PEM }}
        HOST: ${{ secrets.EC2_PUBLIC_IP }}
        USERNAME: ${{secrets.USERNAME }}
      run: |
        echo "$PRIVATE_KEY" > irfan22.pem
        chmod 600 irfan22.pem
        ssh -o StrictHostKeyChecking=no -i irfan22.pem $ubuntu@3.109.121.235 << 'EOF'
        cd /home/ubuntu/app
        npm install
        pm2 restart server.js || pm2 start server.js
        EOF
