name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with: 
        node-version: '18'

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.ID_RSA_PRI }}

    - name: Connect to EC2 and Deploy
      env:
        PRIVATE_KEY: ${{ secrets.ID_RSA_PUB }}
        HOST: ${{ secrets.EC2_HOST }}
        USERNAME: ${{secrets.EC2_USER }}
      run: |
        ssh -i irfan22.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
        cd /home/ec2-user/app
        npm install
        pm2 restart server.js || pm2 start server.js
        EOF
