#deploy to ec2
name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t test_app_image .

    - name: Save Docker image as tar
      run: |
        docker save test_app_image > test_app_image.tar

    - name: Upload Docker image to EC2 and deploy
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.IRFAN22_PEM }}

    - name: Copy Docker image to EC2
      env:
        HOST: ${{ secrets.EC2_PUBLIC_IP }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        scp -o StrictHostKeyChecking=no test_app_image.tar $USERNAME@$HOST:/home/ubuntu/

    - name: SSH into EC2 and run Docker container
      env:
        HOST: ${{ secrets.EC2_PUBLIC_IP }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        ssh -o StrictHostKeyChecking=no $USERNAME@$HOST << 'EOF'
          docker load < /home/ubuntu/test_app_image.tar
          docker stop test_app_container || true
          docker rm test_app_container || true
          docker run -d --name test_app_container -p 3000:3000 test_app_image
        EOF
